#!/bin/sh
#
# GLOBAL SH FUNCTIONS
#

# Get colors from lifepillar GIST, 24-bit-color.sh; // Have not verified the latest version nor integrity but it works
# Other url may be provided with the [ --url URL ] option
# Function will test if given URL is present,
#
get_colors_sh()
{
    display_help()
    {
        printf "%s\n" "get_colors_sh [-h|help] [--url URL]"
    }

    display_error()
    {
        display_help
        
        printf "ERROR: %s\n" "$1"
    }

    local o="h"
    local l="help,url:"
    
    local src="https://gist.githubusercontent.com/lifepillar/09a44b8cf0f9397465614e622979107f/raw/24-bit-color.sh"
    
    ARGS=$(getopt --options $o --longoptions $l -- "$@")
    
    if [ $? != 0 ]; then 
      display_error "ERROR: Missing argument"
      unset ARGS
        
      exit 1; 
    fi
         
    eval set -- "$ARGS"
    unset ARGS

    while true; do
        case "$1" in
        -h|--help) 
            display_help       
            return 0
            ;;
        --url)
            shift
            if [ "${1:0:1}" = "-" ]; then
              display_error "ERROR: Bad argument"
              return 1
            fi

            src="$1"
            ;;
        --)
            shift
            break;;
        ?)
            return 1
            ;;
        esac
        shift
    done
    
    if [ ! $(echo "$src" | grep -c -E "^https://") != 0 ]; then
      display_error "ERROR: Bad URL"

      return 1
    fi

    REQ=$(curl -s $src)
    
    if [ $? != 0 ]; then 
      display_error "ERROR: curl Error"
      unset REQ

      return 1
    fi
    

    if [ ! $(echo "$REQ" | grep -c -E "^#!/bin/.+sh") != 0 ]; then 
      display_error "ERROR: Bad executable" 
      unset REQ

      return 1
    fi

    echo "$REQ"

    unset REQ

    return 0
}

