#!/bin/sh

function ssh_kitty () {
    if [[ "${TERM}" == "xterm-kitty" ]]; then
        kitty +kitten ssh ${@}
    fi
}

function get_os() {
    local OS=$(uname -s)

    case "$OS" in
        Linux)
            if [ -f /etc/os-release ]; then
                source /etc/os-release
                echo $ID
            fi
            ;;
        FreeBSD)
            echo "FreeBSD"
            ;;
        Darwin)
            echo "macOS"  # also BSD-ish, in case you care
            ;;
        *)
            echo "Unknown OS: $OS"
            ;;
    esac
}
